# Q1

In [20]:
import numpy as np
arr = np.array([1, 2, 3])
list1 = arr.tolist()
print(list1)

[1, 2, 3]


# Q2

In [26]:
import numpy as np

x,y = 3,4
a = np.arange(x*y).reshape(x,y)
print (a)
diags =  [a[::-1,:].diagonal(i) for i in range(-a.shape[0]+1,a.shape[1])] 
#print (diags)
diags.extend(a.diagonal(i) for i in range(a.shape[1]-1,-a.shape[0],-1))
print  (diags)




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([0]), array([4, 1]), array([8, 5, 2]), array([9, 6, 3]), array([10,  7]), array([11]), array([3]), array([2, 7]), array([ 1,  6, 11]), array([ 0,  5, 10]), array([4, 9]), array([8])]


# Q3

In [9]:
import numpy as np
n = np.array([[1, 10],[2,6]])
x = 3
print(n > x)
print(n == x)
print(n < x)


[[False  True]
 [False  True]]
[[False False]
 [False False]]
[[ True False]
 [ True False]]


# Q4

In [ ]:
import numpy as np
x= np.array ([1,2,3])
y = np.array([5,6,7])
d = (x + y)
print (d)

In [60]:
import numpy as np
np_array = np.arange(2*3*3).reshape(2,3,3)
print("Original Numpy array:")
print (np_array)
result = np.diagonal(np_array, axis1=1, axis2=2)
a= sum(result)
print(a)

Original Numpy array:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
51


In [18]:
import numpy as np
#print("Original matrix:\n")
X = np.random.rand(2,2)
#print(X)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)
    

[[ 0.05071957 -0.05071957]
 [-0.10263598  0.10263598]]
